//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSQL_Stored_SP
{


	public partial class DynamicSQLInStoredProcedure
	{

		/// <summary>
		/// form1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;


		protected global::System.Web.UI.HtmlControls.HtmlInputText inputFirstname ;


		protected global::System.Web.UI.HtmlControls.HtmlInputText inputLastname;


		protected global::System.Web.UI.HtmlControls.HtmlInputText inputGender;


		protected global::System.Web.UI.HtmlControls.HtmlInputText inputSalary;


		protected global::System.Web.UI.HtmlControls.HtmlInputText gvSearchResults;
	}
}

